root: true
env:
  browser: true
  es6: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
extends:
  - eslint:recommended
  - plugin:vue/recommended
  - prettier
rules:
  prettier/prettier:
    - error
    - semi: false
      singleQuote: true
      trailingComma: es5
  no-empty:
    - error
    - allowEmptyCatch: true
  vue/component-name-in-template-casing:
    - error
