root: true
extends:
  - "plugin:vue/recommended"
  - "@vue/standard"
  - "eslint:recommended"
rules:
  indent: [error, 4]
  vue/name-property-casing: "off"
  vue/html-indent: [error, 4]
  no-trailing-spaces: [error]
parserOptions:
  parser: babel-eslint
